import Head from "next/head";
import React, { useState , useEffect } from "react";

export default function Home() {

  const [quotes, setQuotes] = useState("")
  
  const getQuotes = () => {
    fetch("https://type.fit/api/quotes")
      .then((res) => res.json())
      .then((data) => {
        const getRandomQuote = Math.floor(Math.random() * data.length);
        setQuotes(data[getRandomQuote]);
      })
  };

  useEffect(() => {
    getQuotes();
  },[])

  return (
    <div>
      <Head>
        <title>Prtm Quote Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="antialiased">
      <div
      className="h-screen flex flex-col justify-center items-center bg-gradient-to-r from-green-400 via-cyan-400 to-blue-500 p-4"
    >
      <h1 className="text-3xl p-3 font-semibold text-slate-900 mb-10 text-center">
        <span className="text-5xl font-extrabold text-rose-900">Motivational</span
        ><br />
        Quotes
      </h1>
      <div
        className="bg-green-200 shadow-2xl text-2xl font-bold text-center rounded-2xl px-3 h-1/2 w-full justify-center items-center flex flex-col md:w-1/2 md:max-w-[800px]"
          >
            <span className="mb-4 text-blue-900">{quotes.text}</span>
            <span className="text-xl font-semibold text-cyan-900">--{quotes.author}</span>
          
          </div>
          <button
            onClick={getQuotes}
        type="button"
        className="text-lg font-semibold mb-2 w-full inline-block px-6 py-2.5 mt-3 max-w-[800px] bg-cyan-600 text-white leading-normal uppercase rounded-2xl shadow-md hover:bg-cyan-700 hover:shadow-lg focus:bg-cyan-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-cyan-900 active:shadow-lg transition duration-150 ease-in-out"
      >
        Get Quotes
      </button>
    </div>
      </div>
      
    </div>
  );
}
